---
permalink: online-help/concept-network-interface-performance-explorer-page.html 
sidebar: sidebar 
keywords:  
summary: A página Performance/Network Interface Explorer fornece uma visão geral detalhada do desempenho de todos os LIFs dentro de um cluster. 
---
= Página do Explorador de Interface de desempenho/rede
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A página Performance/Network Interface Explorer fornece uma visão geral detalhada do desempenho de todos os LIFs dentro de um cluster.

A página Explorador de Interface de desempenho/rede permite-lhe monitorizar e comparar o desempenho de LIF durante um período de tempo específico, o que o ajuda a resolver problemas e a ajustar o seu desempenho de LIF.

Usando a funcionalidade Ver e comparar, você pode comparar o desempenho desta interface de rede com:

* Outros LIFs que estão na mesma porta
* Outros LIFs que estão no mesmo SVM
* A porta na qual reside o LIF
* O SVM no qual o LIF reside


A página Explorador de Interface de desempenho/rede permite-lhe:

* Veja os problemas relacionados ao limite e seus detalhes
* Acompanhe e compare dados de desempenho de LIF
* Investigue e solucione problemas relacionados ao limite
* Investigue e solucione problemas de desempenho

