---
permalink: online-help/concept-all-workloads.html 
sidebar: sidebar 
keywords: workloads,workloads 
summary: A visualização todos os workloads exibe a lista de todos os workloads disponíveis nos clusters de um data center. 
---
= Todos os workloads
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A visualização todos os workloads exibe a lista de todos os workloads disponíveis nos clusters de um data center.

A visualização todos os workloads lista os workloads de storage associados aos clusters do ONTAP gerenciados pelo Unified Manager. A página também permite que você atribua políticas de eficiência de storage e níveis de serviço de performance a workloads de storage.

Quando você adiciona clusters ao Unified Manager, os workloads de storage em cada cluster são automaticamente descobertos e exibidos nesta página, exceto os volumes do FlexGroup e seus componentes.

O Unified Manager começa a analisar os workloads para recomendação (níveis de serviço de performance recomendados) somente após o início das operações de e/S nos workloads de storage. Para as cargas de trabalho de storage recém-descobertas nas quais não houve operações de e/S, o status é "'aguardando pela e/S'". Depois que as operações de e/S começam nas cargas de trabalho de storage, o Unified Manager inicia a análise e o status da carga de trabalho muda para "'Learning...'". Após a conclusão da análise (em até 24 horas a partir do início das operações de e/S), os níveis de Serviço de desempenho recomendados são exibidos para os workloads de storage.

Usando a opção *cargas de trabalho* > *todas as cargas de trabalho*, você pode executar várias tarefas:

* Adicionar ou provisionar workloads de storage
* Visualize e filtre a lista de cargas de trabalho
* Atribua níveis de serviço de performance a workloads de storage individuais
* Atribua níveis de Serviço de desempenho recomendados pelo sistema a todas as cargas de trabalho não atribuídas
* Atribua políticas de eficiência de storage a workloads de storage




== Adição ou provisionamento de workloads de storage

Você pode adicionar ou provisionar os workloads de storage a LUNs compatíveis (compatíveis com protocolos iSCSI e FCP), compartilhamentos de arquivos NFS e compartilhamentos de SMB.



== Visualização e filtragem de workloads

Na tela todos os workloads, você pode visualizar todos os workloads em seu data center ou pesquisar workloads de storage específicos com base nos níveis de Serviço de Performance atribuídos a eles ou por nomes de workloads. Pode utilizar o ícone de filtro para introduzir condições específicas para a sua pesquisa. Você pode pesquisar por diferentes condições de filtro, como pelo cluster de host ou VM de armazenamento. Se você selecionar a opção *capacidade total*, poderá pesquisar pela capacidade total das cargas de trabalho. O número de cargas de trabalho retornadas pode variar dependendo da condição exata do filtro inserida, já que a capacidade é comparada em um nível de byte. A tela exibe informações de storage para workloads, como o cluster de host e a VM de storage, juntamente com o nível de serviço de desempenho e a Política de eficiência de storage, se houver.

A página também permite visualizar os detalhes de performance de um workload. Você pode exibir informações detalhadas sobre o IOPS, a capacidade e a latência da carga de trabalho clicando no botão *escolher / pedir colunas* e selecionando colunas específicas para exibir. A coluna Exibição de desempenho exibe as IOPS média e pico de uma carga de trabalho e você pode clicar no ícone do analisador de carga de trabalho para exibir a análise detalhada de IOPS. O botão *Analyze Workload* na janela pop-up análise de IOPS leva você à página análise de cargas de trabalho, onde você pode selecionar um intervalo de tempo e exibir as tendências de latência, taxa de transferência e capacidade para a carga de trabalho selecionada. Para obter mais informações sobre o analisador de carga de trabalho, consulte _Troubleshooting cargas de trabalho usando o analisador de carga de trabalho_

link:concept-troubleshooting-workloads-using-the-workload-analyzer.html["Solução de problemas de cargas de trabalho usando o analisador de carga de trabalho"]



== Atribuição de níveis de Serviço de Performance a workloads de storage

Você pode atribuir um nível de Serviço de Performance a um ou vários workloads de storage. Usando as diferentes navegações na tela, você pode atribuir um nível de Serviço de desempenho específico ou recomendado pelo sistema às cargas de trabalho.



== Atribuição de níveis de Serviço de desempenho recomendados pelo sistema a todas as cargas de trabalho não atribuídas

Você pode atribuir níveis de Serviço de Performance a todos os workloads de storage em um data center que não tenha PSLs atribuídas, desde que haja níveis de Serviço de desempenho recomendados pelo sistema disponíveis para os workloads. Essa funcionalidade não é efetiva para workloads que não têm nenhum nível de Serviço de Performance recomendado pelo sistema disponível. Para usar essa funcionalidade, clique no botão *Assign System Recommended PSLs* (atribuir PSLs recomendados pelo sistema). O sistema avalia internamente os níveis de Serviço de desempenho apropriados para os workloads de storage não atribuídos e exibe o número total de workloads nos quais os níveis de Serviço de desempenho podem ser atribuídos.



== Atribuição de políticas de eficiência de storage a workloads de storage

Você pode atribuir uma política de eficiência de storage a um ou vários workloads de storage. Usando as diferentes navegações na tela, você pode atribuir uma política de eficiência de storage específica aos workloads de storage.



== Atribuindo juntos o nível de Serviço de desempenho e a Política de eficiência de storage

Você pode atribuir um nível de Serviço de Performance e uma Política de eficiência de storage a um único workload em conjunto. Siga estes passos:

. Clique no ícone de edição da linha e, em seguida, clique em *Editar*.
+
Os campos *nível de Serviço de desempenho atribuído* e *Política de eficiência de armazenamento* estão ativados.

. Selecione o nível de Serviço de desempenho necessário e a Política de eficiência de storage.
. Clique no ícone de verificação para aplicar as alterações.




== Análise de critérios de performance e capacidade de um workload

Você pode exibir informações de desempenho sobre uma carga de trabalho para ajudar na solução de problemas clicando no ícone do gráfico de barras na coluna *Exibição de desempenho*. Para visualizar gráficos de desempenho e capacidade na página análise de workload para analisar o objeto, clique no botão *Analyze Workload*.
