---
permalink: online-help/concept-storage-vm-performance-explorer-page.html 
sidebar: sidebar 
keywords:  
summary: 'A página Performance/SVM Explorer fornece uma visão geral detalhada do desempenho de todas as máquinas virtuais de storage (SVMs) em um cluster.' 
---
= Página VM de storage/Explorador de performance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A página Performance/SVM Explorer fornece uma visão geral detalhada da performance de todas as máquinas virtuais de storage (SVMs) em um cluster.

A página Storage VM/performance permite controlar e comparar a performance da SVM durante um período de tempo específico, o que ajuda você a solucionar problemas e ajustar a performance do SVM.

Usando a funcionalidade Exibir e comparar, você pode comparar o desempenho desta VM de armazenamento com:

* Outros SVMs no mesmo cluster
* Volumes nesta SVM
* Interfaces de rede neste SVM


A página Storage VM/Performance (VM/performance de storage) permite:

* Veja os problemas relacionados ao limite e seus detalhes
* Acompanhe e compare os dados de performance do SVM
* Investigue e solucione problemas relacionados ao limite
* Investigue e solucione problemas de desempenho

