---
permalink: online-help/reference-types-of-reports.html 
sidebar: sidebar 
keywords:  
summary: Lista abrangente de visualizações e páginas de inventário disponíveis como relatórios que você pode personalizar, salvar, baixar e agendar. 
---
= Tipos de relatórios
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lista abrangente de visualizações e páginas de inventário disponíveis como relatórios que você pode personalizar, salvar, baixar e agendar.



== Relatórios do Active IQ Unified Manager

[cols="1a,1a"]
|===
| Tipo | Objeto de storage ou rede 


 a| 
Capacidade
 a| 
Clusters

Agregados

Volumes

Qtrees



 a| 
Saúde
 a| 
Clusters

Nós

Agregados

VMs de storage

Volumes

Compartilhamentos SMB/CIFS

Compartilhamentos NFS



 a| 
Desempenho
 a| 
Clusters

Nós

Agregados

VMs de storage

Volumes

LUNs

Namespaces NVMe

Interfaces de rede (LIFs)

Portas



 a| 
Qualidade do serviço
 a| 
Grupos de políticas de QoS tradicionais

Grupos de políticas de QoS adaptáveis

Grupos de política de objetivo de nível de serviço de performance



 a| 
Relações de proteção de volume (disponível na página volumes)
 a| 
Todos os relacionamentos

Último estado de transferência de 1 meses

Último 1 mês taxa de transferência

|===