---
permalink: online-help/reference-logical-interface-events.html 
sidebar: sidebar 
keywords:  
summary: Os eventos de LIF fornecem informações sobre o status de seus LIFs, para que você possa monitorar possíveis problemas. Os eventos são agrupados por área de impactos e incluem o nome do evento e da armadilha, o nível de impactos, o tipo de origem e a gravidade. 
---
= Eventos de interface lógica (LIF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os eventos de LIF fornecem informações sobre o status de seus LIFs, para que você possa monitorar possíveis problemas. Os eventos são agrupados por área de impactos e incluem o nome do evento e da armadilha, o nível de impactos, o tipo de origem e a gravidade.



== Área de impactos: Disponibilidade

[cols="1a,1a,1a,1a"]
|===
| Nome do evento (Nome da armadilha) | Nível de impactos | Tipo de origem | Gravidade 


 a| 
Status de LIF para baixo (ocumEvtLifStatusDown)
 a| 
Risco
 a| 
Interface
 a| 
Erro



 a| 
Failover de LIF não possível (ocumEvtLifFailoverNotPossible)
 a| 
Risco
 a| 
Interface
 a| 
Aviso



 a| 
LIF não está na porta de casa(ocumEvtLifNotAtHomePort)
 a| 
Risco
 a| 
Interface
 a| 
Aviso

|===


== Área de impactos: Configuração

[cols="1a,1a,1a,1a"]
|===
| Nome do evento (Nome da armadilha) | Nível de impactos | Tipo de origem | Gravidade 


 a| 
Rota LIF não configurada (não aplicável)
 a| 
Evento
 a| 
Interface
 a| 
Informações

|===


== Área de impactos: Desempenho

[cols="1a,1a,1a,1a"]
|===
| Nome do evento (Nome da armadilha) | Nível de impactos | Tipo de origem | Gravidade 


 a| 
Limite crítico de MB/s violado(ocumNetworkLifMbpsIncident)
 a| 
Incidente
 a| 
Interface
 a| 
Crítico



 a| 
Limite de aviso de MB/s de interface de rede violado(ocumNetworkLifMbpsWarning)
 a| 
Risco
 a| 
Interface
 a| 
Aviso



 a| 
Limite crítico de MB/s violado(ocumFcpLifMbpsIncident)
 a| 
Incidente
 a| 
Interface
 a| 
Crítico



 a| 
Limite de aviso de MB/s violado(ocumFcpLifMbpsWarning)
 a| 
Risco
 a| 
Interface
 a| 
Aviso



 a| 
Limite crítico violado (ocumNvmfFcLifMbpsIncident)
 a| 
Incidente
 a| 
Interface
 a| 
Crítico



 a| 
Limite de aviso de MB/s da interface FCP do NVMf violado(ocumNvmfFcLifMbpsWarning)
 a| 
Risco
 a| 
Interface
 a| 
Aviso

|===