---
permalink: health-checker/concept-configuring-the-destination-and-schedule-for-database-dump-backups.html 
sidebar: sidebar 
keywords:  
summary: Você pode configurar as configurações de backup do banco de dados do Unified Manager para definir o caminho do backup do banco de dados, a contagem de retenção e as programações de backup. Você pode ativar backups programados diários ou semanais. Por padrão, backups programados são desativados. 
---
= Configurar definições de cópia de segurança da base de dados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar as configurações de backup do banco de dados do Unified Manager para definir o caminho do backup do banco de dados, a contagem de retenção e as programações de backup. Você pode ativar backups programados diários ou semanais. Por padrão, backups programados são desativados.



== Antes de começar

* Tem de ter a função Operador, Administrador de aplicações ou Administrador de armazenamento.
* Você deve ter um mínimo de 150 GB de espaço disponível no local que você definir como caminho de backup.
+
É recomendável usar um local remoto externo ao sistema host do Unified Manager.

* Quando o Unified Manager estiver instalado em um sistema Linux, verifique se o usuário "jboss" tem permissões de gravação no diretório de backup.
* Você não deve agendar operações de backup para que ocorram imediatamente após a adição de um novo cluster enquanto o Unified Manager estiver coletando 15 dias de dados históricos de desempenho.




== Sobre esta tarefa

Mais tempo é necessário na primeira vez que um backup é executado do que para backups subsequentes, porque o primeiro backup é um backup completo. Um backup completo pode ter mais de 1 GB e pode levar de três a quatro horas. Backups subsequentes são incrementais e exigem menos tempo.



== Passos

. No painel de navegação à esquerda, clique em *Geral* > *Backup do banco de dados*.
. Na página *Backup do banco de dados*, clique em *Backup Settings*.
. Configure os valores apropriados para um caminho de backup, contagem de retenção e agendamento.
+
O valor padrão para a contagem de retenção é 10; você pode usar 0 para criar backups ilimitados.

. Selecione o botão *programado diariamente* ou *programado semanal* e especifique os detalhes da programação.
. Clique em *aplicar*.

