---
permalink: install-windows/task-changing-the-jboss-password-on-windows.html 
sidebar: sidebar 
keywords:  
summary: Você pode criar uma nova senha JBoss personalizada para substituir a senha padrão definida durante a instalação. Essa tarefa é opcional, mas alguns sites podem exigir esse recurso de segurança para substituir a configuração padrão de instalação do Unified Manager. Esta operação também altera a senha que o JBoss usa para acessar o MySQL. 
---
= Alterar a senha do JBoss
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode criar uma nova senha JBoss personalizada para substituir a senha padrão definida durante a instalação. Essa tarefa é opcional, mas alguns sites podem exigir esse recurso de segurança para substituir a configuração padrão de instalação do Unified Manager. Esta operação também altera a senha que o JBoss usa para acessar o MySQL.



== Antes de começar

* Você deve ter o Privileges de administrador do Windows para o sistema no qual o Unified Manager está instalado.
* Você deve ter a senha para o usuário root MySQL.
* Você deve ser capaz de acessar o script fornecido pelo NetApp `password.bat` no diretório `\Program Files\NetApp\essentials\bin`.




== Passos

. Faça login como usuário admin na máquina host do Unified Manager.
. Use o console dos Serviços do Windows para interromper os seguintes serviços do Unified Manager:
+
** Serviço de aquisição da NetApp Active IQ (Ocie-au)
** Serviço de servidor de gerenciamento NetApp Active IQ (Oncommandsvc)


. Inicie o `password.bat` script para iniciar o processo de alteração de senha: `C:\Program Files\NetApp\essentials\bin> password.bat resetJBossPassword`
. Quando solicitado, insira a senha do usuário raiz do MySQL.
. Quando solicitado, insira a senha atual do usuário do JBoss.
+
A senha padrão é `D11h1aMu@79%`.

. Quando solicitado, digite a nova senha de usuário do JBoss e insira-a novamente para confirmação.
+
As mensagens de confirmação aparecem quando as alterações são feitas e, em seguida, você é solicitado uma última vez para a nova senha de usuário do JBoss.

. Digite a nova senha do usuário do JBoss mais uma vez.
. Quando o script for concluído, inicie os serviços do Unified Manager usando o console do Windows Services:
+
** Serviço de servidor de gerenciamento NetApp Active IQ (Oncommandsvc)
** Serviço de aquisição da NetApp Active IQ (Ocie-au)


. Depois que todos os serviços forem iniciados, você poderá fazer login na IU do Unified Manager.

