---
permalink: install-windows/task-upgrading-to-unified-manager-on-microsoft-windows.html 
sidebar: sidebar 
keywords:  
summary: Você pode atualizar o Unified Manager 9,5 ou 9,6 para 9,7 baixando e executando o arquivo de instalação na plataforma Windows. 
---
= Atualizando o Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode atualizar o Unified Manager 9,5 ou 9,6 para 9,7 baixando e executando o arquivo de instalação na plataforma Windows.



== Antes de começar

* O sistema no qual você está atualizando o Unified Manager deve atender aos requisitos de sistema e software.
+
xref:concept-virtual-infrastructure-or-hardware-system-requirements.adoc[Requisitos do sistema de hardware]

+
xref:reference-windows-software-and-installation-requirements.adoc[Requisitos de software e instalação do Windows]

+
[NOTE]
====
A partir do Unified Manager 9,5, o OpenJDK é fornecido no pacote de instalação e instalado automaticamente. O Oracle Java não é suportado a partir do Unified Manager 9,5.

====
+
[NOTE]
====
A partir do Unified Manager 9,4, é necessário o Microsoft .NET 4.5.2 ou superior. Certifique-se de que tem a versão correta do .NET instalada antes de iniciar a atualização.

====
* Você deve ter o Privileges administrador do Windows. Certifique-se de que o seu nome de utilizador não começa com um ponto de exclamação "!`". Installation of Unified Manager might fail if the user name of user running the installation begins with "`" !".
* Você deve ter credenciais válidas para fazer login no site de suporte da NetApp.
* Para evitar a perda de dados, você deve ter criado um backup da máquina do Unified Manager caso haja algum problema durante a atualização.
* Você deve ter espaço em disco adequado disponível para executar a atualização.
+
O espaço disponível na unidade de instalação deve ser 2,5 GB maior do que o tamanho do diretório de dados. A atualização pára e exibe uma mensagem de erro indicando a quantidade de espaço a ser adicionado se não houver espaço livre suficiente.

* Durante a atualização, você pode ser solicitado a confirmar se deseja manter as configurações padrão anteriores para reter dados de desempenho por 13 meses ou alterá-los para 6 meses. Ao confirmar, os dados históricos de desempenho após 6 meses são purgados.
* Antes de atualizar, deve fechar quaisquer ficheiros ou pastas abertos no `<InstallDir\>\JDK` e `MySQL Data Directory`.




== Sobre esta tarefa

Durante o processo de atualização, o Unified Manager não está disponível. Você deve concluir todas as operações em execução antes de atualizar o Unified Manager.

Se o Unified Manager estiver emparelhado com uma instância do OnCommand Workflow Automation e houver novas versões de software disponíveis para ambos os produtos, será necessário desconetar os dois produtos e configurar uma nova conexão do Workflow Automation após a realização das atualizações. Se você estiver executando uma atualização para apenas um dos produtos, deverá fazer login no Workflow Automation após a atualização e verificar se ele ainda está adquirindo dados do Unified Manager.



== Passos

. Faça login no site de suporte da NetApp e localize a página *Download* para instalar o Gerenciador Unificado na plataforma Windows.
+
https://mysupport.netapp.com/products/index.html[]

. Transfira o ficheiro de instalação do Unified Manager Windows para um diretório de destino no sistema Windows.
. Clique com o botão direito do rato e execute o ficheiro executável do instalador do Unified Manager `(.exe)` como administrador.
+
O Unified Manager solicita a seguinte mensagem:

+
[listing]
----
This setup will perform an upgrade of Unified Manager. Do you want to continue?
----
. Clique em *Yes* e, em seguida, clique em *Next*.
. Digite a senha de root do MySQL8 que foi definida durante a instalação e clique em *Next*.
. Faça login na IU da Web do Unified Manager e verifique o número da versão.




== Depois de terminar

[NOTE]
====
Para executar uma atualização silenciosa do Unified Manager, execute o seguinte comando: `ActiveIQUnifiedManager-<version\>.exe /s /v"MYSQL_PASSWORD=netapp21! /qn /l*v C:\install.log`

====