---
permalink: install-linux/task-removing-unified-manager.html 
sidebar: sidebar 
keywords:  
summary: Se você precisar remover o Unified Manager do host Red Hat Enterprise Linux ou CentOS, poderá parar e desinstalar o Unified Manager com um único comando. 
---
= Remoção do Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você precisar remover o Unified Manager do host Red Hat Enterprise Linux ou CentOS, poderá parar e desinstalar o Unified Manager com um único comando.



== Antes de começar

* Você deve ter acesso de usuário raiz ao servidor a partir do qual deseja remover o Unified Manager.
* O Security-Enhanced Linux (SELinux) deve ser desativado na máquina Red Hat. Altere o modo de tempo de execução do SELinux para "permissivo" usando o `setenforce 0` comando.
* Todos os clusters (fontes de dados) devem ser removidos do servidor do Unified Manager antes de remover o software.




== Passos

. Faça login como usuário raiz no servidor no qual você deseja remover o Unified Manager.
. Pare e remova o Unified Manager do servidor: `rpm -e netapp-um`
+
Esta etapa remove todos os pacotes RPM do NetApp associados. Ele não remove os módulos de software pré-requisito, como Java, MySQL e p7zip.

. Se apropriado, remova os módulos de software de suporte, como Java, MySQL e p7zip: `rpm -e p7zip mysql-community-client mysql-community-server mysql-community-common mysql-community-libs java-x.y`




== Resultados

Após a conclusão desta operação, o software é removido; no entanto, os dados MySQL não são excluídos. Todos os dados do `/opt/netapp/data` diretório são movidos para `/opt/netapp/data/BACKUP` a pasta após a desinstalação.
