---
permalink: install-linux/task-upgrading-mysql-on-linux.html 
sidebar: sidebar 
keywords:  
summary: Você pode atualizar para uma versão mais recente do MySQL no servidor Linux conetado no qual o Unified Manager está instalado para obter correções para vulnerabilidades de segurança. Para qualquer atualização menor, a versão base do MySQL deve ser 8.0.20 ou posterior. Se a versão instalada do MySQL no seu sistema for anterior à 8,0.20, o processo de atualização do Unified Manager 9,7 atualiza automaticamente o MySQL para 8,0.20. Você não deve executar uma atualização autônoma do MySQL de uma versão anterior para 8,0.20. 
---
= Atualizando MySQL no Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode atualizar para uma versão mais recente do MySQL no servidor Linux conetado no qual o Unified Manager está instalado para obter correções para vulnerabilidades de segurança. Para qualquer atualização menor, a versão base do MySQL deve ser 8.0.20 ou posterior. Se a versão instalada do MySQL no seu sistema for anterior à 8,0.20, o processo de atualização do Unified Manager 9,7 atualiza automaticamente o MySQL para 8,0.20. Você não deve executar uma atualização autônoma do MySQL de uma versão anterior para 8,0.20.



== Antes de começar

[NOTE]
====
A atualização manual do MySQL é aplicável apenas para sistemas ligados à Internet. Se a versão instalada do MySQL no seu sistema é 5,7, então você não deve tentar atualizar diretamente o MySQL para a versão 8,0.20. Isso resulta em perda de dados da aplicação.

====
Você precisa ter o Privileges raiz para o sistema Linux no qual o Unified Manager está instalado.



== Sobre esta tarefa

Você pode atualizar a versão base do MySQL 8.0.20 para versões posteriores apenas para pequenas atualizações.



== Passos

. Faça login como usuário raiz na máquina host do Unified Manager.
. Baixe o pacote mais recente do MySQL Community Server `.rpm` no sistema de destino.
. Descompacte o bundle para um diretório no sistema de destino.
. Você obtém vários `.rpm` pacotes no diretório depois de reiniciar o pacote, mas o Unified Manager só precisa dos seguintes pacotes rpm:
+
** mysql-community-client-8.0.20
** mysql-community-libs-8.0.20
** mysql-community-server-8.0.20
** mysql-community-common-8.0.20
** mysql-community-libs-compat-8.0.20


+
Exclua todos os outros `.rpm` pacotes. No entanto, instalar todos os pacotes em um pacote rpm não causa erros.

. Pare o serviço Unified Manager e o software MySQL associado na ordem mostrada:
. Invoque a atualização do MySQL usando o seguinte comando: `yum install *.rpm`
+
`*.rpm` Refere-se aos `.rpm` pacotes no diretório em que você baixou a versão mais recente do MySQL.

. Inicie o Unified Manager na ordem mostrada:

